M48
; DRILL file {KiCad 8.0.1} date 2024-04-18T20:24:52-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-18T20:24:52-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X5.7898Y-3.8024
X6.0173Y-3.8024
T2
X5.5886Y-4.2293
X5.5886Y-4.497
M30
