M48
; DRILL file {KiCad 8.0.1} date 2024-04-06T15:46:51-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-06T15:46:51-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.8343Y-3.4811
X5.0618Y-3.4811
T2
X4.0945Y-2.5433
X4.0945Y-2.811
M30
